name: kanji
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  file: ^7.0.1
  google_generative_ai: ^0.4.6
  mime: ^2.0.0
  yaml: ^3.1.3

dev_dependencies:
  leancode_lint: ^15.1.0
